easy_admin:
  entities:
    Attachment:
      class: App\Entity\Attachment

      list:
        help: 'The items in this entity can NOT be deleted here, Products must be = 0'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','image','projects']
      form:
        fields:
          - {property: 'image'}
          - {property: 'projects'}
