easy_admin:
  entities:
    Attachment:
      class: App\Entity\Attachment
      list:
        title: "All development projects"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','projects', { property: 'image', type: 'image', base_path: '%app.path.project_images%',label: 'Photo' },'createdAt','updatedAt']
        filters: ['projects']
      form:
        fields:
          - {property: 'imageFile', type: 'vich_image', label: 'Image'}
          - {property: 'updatedAt', type_options: { widget: 'single_text' }}
          - {property: 'createdAt', type_options: { widget: 'single_text' }}
      show:
        fields:
          - {property: 'projects'}
          - {property: 'image', type: 'image', base_path: '%app.path.project_images%' }
