easy_admin:
  entities:
    Category:
      class: App\Entity\Category

      list:
        title: "All development projects"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','categoryName','categoryDesc','technology']
        filters: ['technology']
      form:
        fields:
          - {property: 'categoryName'}
          - {property: 'categoryDesc', type: 'text_editor',label: 'Description de la catégorie'}
      show:
        fields:
          - {property: 'categoryName'}
          - {property: 'technology'}
          - {property: 'categoryDesc', type: 'raw'}
