easy_admin:
  entities:
    Category:
      class: App\Entity\Category

      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','categoryName','categoryDesc','technology']
      form:
        fields:
          - {property: 'categoryName'}
          - {property: 'categoryDesc'}
          - {property: 'technology'}
