easy_admin:
  entities:
    Picture:
      class: App\Entity\Picture

      list:
        help: 'The items in this entity can NOT be deleted here, Products must be = 0'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','pictureFile', { property: 'pictureFile', type: 'image', base_path: '%app.path.project_images%',label: 'Photo' }, 'createdAt','updatedAt','project']
      form:
        fields:
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
          - {property: 'project'}
          - {property: 'imageFile', type: 'vich_image'}
      show:
        fields:
          - {property: 'pictureFile', type: 'image', base_path: '%app.path.project_images%' }
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
