easy_admin:
  entities:
    Project:
      class: App\Entity\Project
      list:
        title: "All development projects"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','projectName','attachments','projectDesc', 'tools','technologies' ,'createdAt','updatedAt']
        filters: ['tools', 'technologies']
      show:
        fields:
          - {property: 'projectName'}
          - {property: 'projectDesc', type: 'raw'}
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
          - {property: 'tools'}
          - {property: 'technologies'}
          - {property: 'attachments', template: 'admin/Projects/_images.html.twig' }
      form:
        fields:
          - {type: 'group', label: 'General',icon: 'pencil', css_class: 'col-md-8'}
          - {property: 'projectName'}
          - {property: 'createdAt', type_options: { widget: 'single_text' }}
          - {property: 'updatedAt', type_options: { widget: 'single_text' }}
          - {type: 'section'}
          - {property: 'projectDesc', type: 'text_editor',label: 'Description du projet'}
          - {type: 'group', label: 'Options',css_class: 'col-md-4'}
          - {property: 'technologies'}
          - {property: 'tools'}
          - {type: 'section', label: 'Fichiers joints'}
          - {property: 'attachments', label: 'Attachments', type: 'collection', type_options: {entry_type: 'App\Form\Admin\ImageType', by_reference: false, label: false} }

