easy_admin:
  entities:
    Project:
      class: App\Entity\Project
      list:
        title: "All development projects"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','projectName','attachments','projectDesc', 'tools','technologies' ,'createdAt','updatedAt']
        filters: ['tools', 'technologies']
      show:
        fields:
          - {property: 'projectName'}
          - {property: 'projectDesc', type: 'raw'}
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
          - {property: 'tools'}
          - {property: 'technologies'}
          - {property: 'attachments', template: 'admin/Projects/_images.html.twig' }
      form:
        fields:
          - {type: 'group', label: 'General',icon: 'pencil', css_class: 'col-md-6'}
          - {property: 'projectName'}
          - {property: 'projectDesc', type: 'text_editor'}
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
          - {type: 'group', label: 'Options',css_class: 'col-md-5'}
          - {property: 'tools'}
          - {property: 'technologies'}
          - {type: 'group', label: 'Attachments',css_class: 'col-md-5', icon: 'clip'}
          #          - {property: 'attachments'}
          - {property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\Admin\ImageType', by_reference: false} }

