easy_admin:
  entities:
    Technology:
      class: App\Entity\Technology

      list:
        title: "All development projects"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','technoName',{ property: 'image', type: 'image', base_path: '%app.path.techno_images%',label: 'Logo'} ,'createdAt','updatedAt','project','category']
        filters: ['project']
      form:
        fields:
          - {property: 'technoName'}
          - {property: 'technoDesc', type: 'text_editor',label: 'Description de la tecnhologie'}
          - {property: 'imageFile', type: 'vich_image', label: 'Image'}
          - {property: 'category'}
          - {property: 'createdAt', type_options: { widget: 'single_text' }}
          - {property: 'updatedAt', type_options: { widget: 'single_text' }}
      show:
        fields:
          - {property: 'technoName'}
          - {property: 'technoDesc', type: 'raw'}
          - {property: 'project'}
          - {property: 'category'}
          - {property: 'image', type: 'image', base_path: '%app.path.techno_images%' }
