easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','username','userEmail','createdAt']
      form:
        fields:
          - {property: 'username'}
          - {property: 'userEmail'}
          - {property: 'createdAt'}
